### ISSUE TITLE
React Native for Web doesn't fire

### ISSUE THREAD

**Issue by TomOMara** [jakex7/react-native-click-outside#3]
Hi Jake, cool library! 

This works really well on ios, but when testing the readme example in a react-native-web application, the console log didn't fire.

```
export default function MyComponent() {
  const ref = useClickOutside<View>(() => console.log('clicked outside A'));
  return (
    <View ref={ref}>
      <Text>Test</Text>
    </View>
  );
}
```

Any thoughts?

**Comment by TomOMara** [comment]
Presumably latest version needs to be released on npm? 👀

**Comment by jakex7** [comment]
Hey @TomOMara,
you are right, at that time the version was not released because it was in the testing phase. It was released May 17, but unfortunately I missed the issue. Sorry for the lack of response.
Feel free to test and if there is anything I can help you with, please let me know 😃
